In [1]:
#NumPy is the fundamental package for scientific computing in Python.
#It is a Python library that provides a multidimensional array object, various derived objects and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [15]:
#Numpy is a library that used for computing scientific/mathematical data. Other usages are in:

#- Numerical Analysis
#- Linear algebra
#- Matrix computations



In [16]:
#features of Numpy-

#NumPy stands on CPython, a non optimizing bytecode interpreter.
#Multidimensional arrays.
#Functions andoperators for these arrays
#Python alternatives to MATLAB.
#ndarray- n-dimensional arrays.
#Fourier transformsand shapes manipulation.
#Linear algebra and random number generation.

In [10]:
#why we need numpy?
#Since, Python does not have built-in support for Arrays, but Python lists can be used instead:


array = ['hello', 'Hi']
print(array)

#but its not an array* it's still a lst

['hello', 'Hi']


In [8]:
# create an array

import numpy as numbers
a = numbers.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [11]:
# for the 2D, 3D etc arrays in Numpy to calculate big data in terms of including columns and rows:

import numpy as numbers
a = numbers.array([(0,1,2,3,4,5),(6,7,8,9,10,11)])
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [12]:
#*To know the dimension of the array whether it's is 2D 3D or more simply:

print(a.ndim)

2


In [13]:
#To know the size of an array

print(a.size)

12


In [14]:
#To know the shape of an array:
print(a.shape)
#ti will tell rows and column

(2, 6)
